controller_list:
 - name: multi_dof_joint_trajectory_action
   type: MultiDofFollowJointTrajectory
   default: true
   joints:
     - virtual_joint

 - name: balsa_arm_controller
   action_ns: follow_joint_trajectory
   type: FollowJointTrajectory
   default: true
   joints:
     - shoulder
     - elbow
     - wrist
